#:schema https://docs.jj-vcs.dev/latest/config-schema.json

[user]
name = "David Pitoniak"
email = "davidpitoniak32@gmail.com"

[ui]
diff-editor = ":builtin"
default-command = "log"
# not sure yet, taken from chriskrycho
log-word-wrap = true
diff-instructions = false

[signing]
behavior = "own"
backend = "gpg"
key = "1C0FB72620F12C792A015A38F37BD0CEA2ADFAA9"

[git]
sign-on-push = true
private-commits = "wip | testing | integration"

[revset-aliases]
wip = 'description(regex:"^\\[(wip|WIP|todo|TODO|spike)\\]|(wip|WIP|todo|TODO|spike):?")'
testing = '(description(regex:"^testing:"))'
integration = 'description("[integration]") | description("[integration merge]")'

[aliases]

# taken from chriskrycho
# l = ["log", "-r", "trunk()::"]
l = ["log"]
lall = ["log", "-r", "..all()"]

# https://danverbraganza.com/writings/most-frequent-jj-commands

# It updates the closest bookmark ancestor to point to the current revision, giving me an easy command to type before I jj git push
# tug- updates the bookmark to the previous revision, while tug updates it to the current one.
tug = ["bookmark", "move", "--from", "heads(::@- & bookmarks())", "--to", "@"]
tug- = ["bookmark", "move", "--from", "heads(::@- & bookmarks())", "--to", "@-"]

# jj mine prints out the bookmarks/branches that I am currently working on, when I want to take stock and switch between them.
mine = ["bookmark", "list", "-r", "mine()"]
