#:schema https://docs.jj-vcs.dev/latest/config-schema.json

[user]
name = "David Pitoniak"
email = "davidpitoniak32@gmail.com"

[signing]
behavior = "own"
backend = "gpg"
key = "1C0FB72620F12C792A015A38F37BD0CEA2ADFAA9"
